FROM node:18-bullseye-slim
WORKDIR /srv
ARG UID=1000
# RUN groupadd truffle && useradd -m -u ${UID} t-dev && usermod -G truffle t-dev && \
RUN  npm install -g npm && chgrp -R node /usr/ && chmod 770 -R /usr && chmod 770 -R /srv
USER ${UID}

RUN npm install -g truffle