version: '3.6'
services:
  truffle:
    container_name: truffle
    build: ./truffle
    ports:
      - "8888:8888"
    tty: true
    volumes:
      - ../app:/srv/:cached
  ganache:
    container_name: ganache
    build: ./ganache
    ports:
       - "8545:8545"
    stdin_open: true
    tty: true
# volumes:
#   mysql_db:
#     driver: local